name = "GraphsOfConvexSets"
uuid = "823ad9d2-5d47-4587-a0bc-029103bd504c"
version = "0.1.0"

[deps]
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Hypatia = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Pajarito = "2f354839-79df-5901-9f0a-cdb2aac6fe30"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
GraphPlot = "0.6.2"
Graphs = "1"
HiGHS = "1.20.1"
Hypatia = "0.9.1"
JuMP = "1.28.0"
LinearAlgebra = "1.10"
MathOptInterface = "1.42.0"
Pajarito = "0.8.2"
Revise = "3.13.2"
julia = "1.10"
